name: Lint (Pylint)

on:
  push:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pylint (fail if score below threshold)
        run: |
          # Lint both src/ and (optionally) tests/
          pylint src --fail-under=9.5
